#!/bin/sh
# Paperless-ngx s6 service

readonly log_prefix="[paperlessngx]"

echo "${log_prefix} Starting paperless-ngx..."

HOME=/config; export HOME
LANG=en_US.UTF-8; export LANG

# Standard start command for paperless-ngx
exec /usr/local/bin/s6-notifyoncheck -c /healthz /usr/local/bin/s6-setuidgid bsd \
     cd /app/src/src /app/venv/bin/python -m granian \
     --interface asginl --ws --loop uvloop paperless.asgi:application