#!/bin/sh
# Daemonless standard healthcheck for paperless-ngx

# Standard Mode: Check /ready or HTTP endpoint
if fetch -o /dev/null "http://127.0.0.1:8000/" >/dev/null 2>&1; then
    exit 0
else
    exit 1
fi
