#!/bin/sh
# Paperless-ngx flower s6 service

readonly log_prefix="[flower]"

echo "${log_prefix} Starting flower..."

LANG=en_US.UTF-8; export LANG

# Standard start command for paperless-ngx
if [ "x${PAPERLESS_ENABLE_FLOWER}" != "x" ]; then
    # Small delay to allow celery to be up first
    echo "${log_prefix} Starting flower in 5s"
    sleep 5

    exec /usr/local/bin/s6-setuidgid bsd cd /app/src \
         /app/.local/bin/celery --app paperless flower --url-prefix=flower --loglevel INFO
else
    echo "${log_prefix} Not starting flower"
    # https://skarnet.org/software/s6/s6-svc.html
    s6-svc -Od .
fi

