#!/bin/sh
# Create directories for paperless-ngx

# Ensure directories exist and have correct ownership
mkdir -p /config/consume /config/data /config/media
chown -R bsd:bsd /config

# Run a DB migration to make sure the database is initialized
# and updated to the latest schema.
echo [paperlessngx-migration] Running DB migration
s6-setuidgid bsd cd /app/src /usr/local/bin/python3.12 manage.py migrate

# Create superuser if env variable is defined
if [ "x${PAPERLESS_ADMIN_USER}" != "x" ]; then
  s6-setuidgid bsd cd /app/src /usr/local/bin/python3.12 manage.py manage_superuser

  echo "[paperlessngx-superuser] Superuser creation done"

else
  echo "[paperlessngx-superuser] Not creating superuser"
fi
